//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImprezGarage.Infrastructure.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ImprezGarageEntities : DbContext
    {
        public ImprezGarageEntities()
            : base("name=ImprezGarageEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<VehicleType> VehicleTypes { get; set; }
        public virtual DbSet<Vehicle> Vehicles { get; set; }
        public virtual DbSet<MaintenanceCheck> MaintenanceChecks { get; set; }
        public virtual DbSet<MaintenanceCheckType> MaintenanceCheckTypes { get; set; }
        public virtual DbSet<PartsReplacementRecord> PartsReplacementRecords { get; set; }
        public virtual DbSet<PetrolExpense> PetrolExpenses { get; set; }
    }
}
