//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImprezGarage.Infrastructure.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaintenanceCheckOption
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MaintenanceCheckOption()
        {
            this.MaintenanceOptionsPerformeds = new HashSet<MaintenanceOptionsPerformed>();
        }
    
        public int Id { get; set; }
        public int MaintenanceType { get; set; }
        public string Name { get; set; }
        public string Notes { get; set; }
    
        public virtual MaintenanceCheckType MaintenanceCheckType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MaintenanceOptionsPerformed> MaintenanceOptionsPerformeds { get; set; }
    }
}
