//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImprezGarage.Infrastructure.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaintenanceOptionsPerformed
    {
        public int Id { get; set; }
        public int MaintenanceCheck { get; set; }
        public int MaintenanceOption { get; set; }
        public Nullable<bool> IsChecked { get; set; }
        public string Notes { get; set; }
    
        public virtual MaintenanceCheckOption MaintenanceCheckOption { get; set; }
        public virtual MaintenanceCheck MaintenanceCheck1 { get; set; }
    }
}
