//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImprezGarage.Infrastructure.Services
{
    using System;
    using System.Collections.Generic;
    
    public partial class PetrolExpense
    {
        public int Id { get; set; }
        public Nullable<double> Amount { get; set; }
        public Nullable<System.DateTime> DateEntered { get; set; }
        public Nullable<int> VehicleId { get; set; }
    }
}
